import { Gender } from "../../enum/Gender";
import { Title } from "../../enum/Title";
import { CardDto } from "./CardDto";
import { FaceDto } from "./FaceDto";
import { LicensePlateDto } from "./LicensePlateDto";
import { PinDto } from "./PinDto";
import { QrCodeDto } from "./QrCodeDto";

export interface UserDto {
  guid: string;
  username: string;
  password: string;
  identification: string;
  title: Title;
  firstname: string;
  middlename: string;
  lastname: string;
  gender: Gender;
  dateOfBirth: Date;
  email: string;
  phone: string;
  isOperator: boolean;
  isUser: boolean;
  roleGuid: string;
  role: string;
  companyGuid: string;
  company: string;
  departmentGuid: string;
  department: string;
  positionGuid: string;
  position: string;
  address: string;
  joinedDate: Date;
  expiredDate: Date;
  additionals: string[];
  groups: string[];
  cards: CardDto[];
  licensePlates: LicensePlateDto;
  pins: PinDto;
  qrCodes: QrCodeDto;
  face: FaceDto;
  locations: string[];
  isDefault: boolean;
  isActive: boolean;
}
