import { Gender } from "../../enum/Gender";
import { Title } from "../../enum/Title";
import { CardDto } from "./CardDto";
import { FaceDto } from "./FaceDto";
import { LicensePlateDto } from "./LicensePlateDto";
import { PinDto } from "./PinDto";
import { QrCodeDto } from "./QrCodeDto";
import { UserMetadata } from "./UserMetadata";

export interface UserDto {
  guid: string;
  userCode: string;
  username: string;
  password: string;
  identification: string;
  title: Title;
  firstname: string;
  middlename: string;
  lastname: string;
  gender: Gender;
  dateOfBirth: Date;
  email: string;
  phone: string;
  roleGuid: string | null;
  role: string;
  companyGuid: string | null;
  company: string;
  departmentGuid: string | null;
  department: string;
  positionGuid: string | null;
  position: string;
  address: string;
  joinedDate: Date;
  expiredDate: Date;
  additionals: string[];
  groups: string[];
  cards: CardDto[];
  licensePlate: LicensePlateDto;
  pin: PinDto;
  qrCode: QrCodeDto;
  face: FaceDto;
  locations: string[];
  isDefault: boolean;
  isActive: boolean;
  metadata:string | UserMetadata;
}
