<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Contracts\Adapter.Contract\Adapter.Contract.csproj" />
    <ProjectReference Include="..\Aero.Domain\Aero.Domain.csproj" />
  </ItemGroup>

</Project>
