export enum SignalRTopic {
      IDREPORT = "DEVICE.IDREPORT",
      MODULE_STATUS = "DEVICE.MODULE.STATUS",
      CP_STATUS = "DEVICE.OUTPUT.STATUS",
      DEVICE_STATUS = "DEVICE.STATUS",
      EVENT = "EVENT",
      EXCEPTION_EVENT = "EXCEPTION.EVENT",
      ADAPTER_EVENT = "ADAPTER.EVENT",
      CONFIG = "DEVICE.CONFIG"
}

export enum SignalRHub {
      UI = "/notiHubs"
}