namespace Core.Contract.DTOs.Setting;

public sealed record AeroDriverSettingDto(
  Guid Guid,
  int nPorts,
  int nScps,
  int cType,
  int cPort,
  int nMsp1Port,
  int nTransaction,
  int nSio,
  int nMp,
  int nCp,
  int nAcr,
  int nAlvl,
  int nTrgr,
  int nProc,
  int GmtOffset,
  bool IsDaylightSaving,
  int nTz,
  int nHol,
  int nMpg,
  int nTranLimit,
  int nCards,
  int nAlvlPerCard,
  int PinDuressMode,
  int DuressConstDigit,
  int CardIdSize,
  int PinDigit,
  int IssueCodeBit,
  bool ApbLocation,
  int StoreActDate,
  int StoreDeactDate,
  bool UsedLimit,
  int EscortTimeout,
  int MultiCardTimeout
);