// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Setting.Infrastructure.Persistences;

#nullable disable

namespace Setting.Infrastructure.Migrations
{
    [DbContext(typeof(SettingDbContext))]
    [Migration("20260830134325_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("setting")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.PasswordRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("is_digit")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_lower")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_symbol")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_upper")
                        .HasColumnType("boolean");

                    b.Property<int>("len")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("PasswordRules", "setting");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            is_digit = false,
                            is_lower = false,
                            is_symbol = false,
                            is_upper = false,
                            len = 4,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.WeakPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("password_rule_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.HasIndex("password_rule_guid");

                    b.ToTable("WeakPasswords", "setting");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("f371dff7-fa82-4a0f-95ba-f24954cf73f7"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "P@ssw0rd",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("c347ec2d-17e7-4048-82df-9b1b65730669"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "password",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("b3124c81-3c54-46b3-bafd-a945854fc946"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "admin",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("df75695c-6821-49ad-a857-60e1b0763329"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "123456",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.WeakPassword", b =>
                {
                    b.HasOne("Setting.Infrastructure.Persistences.Entities.PasswordRule", "password_rule")
                        .WithMany("weaks")
                        .HasForeignKey("password_rule_guid")
                        .HasPrincipalKey("guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("password_rule");
                });

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.PasswordRule", b =>
                {
                    b.Navigation("weaks");
                });
#pragma warning restore 612, 618
        }
    }
}
