// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Setting.Infrastructure.Persistences;

#nullable disable

namespace Setting.Infrastructure.Migrations
{
    [DbContext(typeof(SettingDbContext))]
    partial class SettingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("setting")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.AeroDriverSetting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("apb_location")
                        .HasColumnType("boolean");

                    b.Property<bool>("apb_time")
                        .HasColumnType("boolean");

                    b.Property<int>("c_port")
                        .HasColumnType("integer");

                    b.Property<int>("c_type")
                        .HasColumnType("integer");

                    b.Property<int>("card_id_size")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("duress_const_digit")
                        .HasColumnType("integer");

                    b.Property<int>("escort_timeout")
                        .HasColumnType("integer");

                    b.Property<int>("gmt_offset")
                        .HasColumnType("integer");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("host_timeout")
                        .HasColumnType("integer");

                    b.Property<bool>("is_daylight_saving")
                        .HasColumnType("boolean");

                    b.Property<int>("issue_code_bit")
                        .HasColumnType("integer");

                    b.Property<int>("multi_card_timeout")
                        .HasColumnType("integer");

                    b.Property<int>("n_acr")
                        .HasColumnType("integer");

                    b.Property<int>("n_alvl")
                        .HasColumnType("integer");

                    b.Property<int>("n_alvl_per_card")
                        .HasColumnType("integer");

                    b.Property<int>("n_cards")
                        .HasColumnType("integer");

                    b.Property<int>("n_cp")
                        .HasColumnType("integer");

                    b.Property<int>("n_hol")
                        .HasColumnType("integer");

                    b.Property<int>("n_mp")
                        .HasColumnType("integer");

                    b.Property<int>("n_mpg")
                        .HasColumnType("integer");

                    b.Property<int>("n_msp1_port")
                        .HasColumnType("integer");

                    b.Property<int>("n_port")
                        .HasColumnType("integer");

                    b.Property<int>("n_proc")
                        .HasColumnType("integer");

                    b.Property<int>("n_scps")
                        .HasColumnType("integer");

                    b.Property<int>("n_sio")
                        .HasColumnType("integer");

                    b.Property<int>("n_tran_limit")
                        .HasColumnType("integer");

                    b.Property<int>("n_trasaction")
                        .HasColumnType("integer");

                    b.Property<int>("n_trgr")
                        .HasColumnType("integer");

                    b.Property<int>("n_tz")
                        .HasColumnType("integer");

                    b.Property<int>("pin_digit")
                        .HasColumnType("integer");

                    b.Property<int>("pin_duress_mode")
                        .HasColumnType("integer");

                    b.Property<int>("store_act_date")
                        .HasColumnType("integer");

                    b.Property<int>("store_deact_date")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("used_limit")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("AeroDriverSettings", "setting");

                    b.HasData(
                        new
                        {
                            id = 1,
                            apb_location = true,
                            apb_time = true,
                            c_port = 3333,
                            c_type = 7,
                            card_id_size = 0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            duress_const_digit = 5,
                            escort_timeout = 15,
                            gmt_offset = -25200,
                            guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            host_timeout = 5,
                            is_daylight_saving = false,
                            issue_code_bit = 1,
                            multi_card_timeout = 15,
                            n_acr = 64,
                            n_alvl = 32000,
                            n_alvl_per_card = 8,
                            n_cards = 200000,
                            n_cp = 388,
                            n_hol = 255,
                            n_mp = 615,
                            n_mpg = 128,
                            n_msp1_port = 3,
                            n_port = 1024,
                            n_proc = 1024,
                            n_scps = 1024,
                            n_sio = 33,
                            n_tran_limit = 60000,
                            n_trasaction = 60000,
                            n_trgr = 1024,
                            n_tz = 255,
                            pin_digit = 6,
                            pin_duress_mode = 2,
                            store_act_date = 2,
                            store_deact_date = 2,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            used_limit = true
                        });
                });

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.PasswordRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("is_digit")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_lower")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_symbol")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_upper")
                        .HasColumnType("boolean");

                    b.Property<int>("len")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("PasswordRules", "setting");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            is_digit = false,
                            is_lower = false,
                            is_symbol = false,
                            is_upper = false,
                            len = 4,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.WeakPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("password_rule_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.HasIndex("password_rule_guid");

                    b.ToTable("WeakPasswords", "setting");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("f371dff7-fa82-4a0f-95ba-f24954cf73f7"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "P@ssw0rd",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("c347ec2d-17e7-4048-82df-9b1b65730669"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "password",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("b3124c81-3c54-46b3-bafd-a945854fc946"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "admin",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            guid = new Guid("df75695c-6821-49ad-a857-60e1b0763329"),
                            password_rule_guid = new Guid("ae243161-6067-47d0-8bcc-1990388bb6e6"),
                            pattern = "123456",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.WeakPassword", b =>
                {
                    b.HasOne("Setting.Infrastructure.Persistences.Entities.PasswordRule", "password_rule")
                        .WithMany("weaks")
                        .HasForeignKey("password_rule_guid")
                        .HasPrincipalKey("guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("password_rule");
                });

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.PasswordRule", b =>
                {
                    b.Navigation("weaks");
                });
#pragma warning restore 612, 618
        }
    }
}
