// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Setting.Infrastructure.Persistences;

#nullable disable

namespace Setting.Infrastructure.Migrations
{
    [DbContext(typeof(SettingDbContext))]
    partial class SettingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("setting")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Setting.Infrastructure.Persistences.Entities.CardFormat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("bits")
                        .HasColumnType("smallint");

                    b.Property<short>("ch_ln")
                        .HasColumnType("smallint");

                    b.Property<short>("ch_loc")
                        .HasColumnType("smallint");

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("fac")
                        .HasColumnType("smallint");

                    b.Property<short>("fc_ln")
                        .HasColumnType("smallint");

                    b.Property<short>("fc_loc")
                        .HasColumnType("smallint");

                    b.Property<short>("flag")
                        .HasColumnType("smallint");

                    b.Property<short>("function_id")
                        .HasColumnType("smallint");

                    b.Property<short>("ic_ln")
                        .HasColumnType("smallint");

                    b.Property<short>("ic_loc")
                        .HasColumnType("smallint");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("offset")
                        .HasColumnType("smallint");

                    b.Property<short>("pe_ln")
                        .HasColumnType("smallint");

                    b.Property<short>("pe_loc")
                        .HasColumnType("smallint");

                    b.Property<short>("po_ln")
                        .HasColumnType("smallint");

                    b.Property<short>("po_loc")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("id");

                    b.ToTable("CardFormats", "setting");

                    b.HasData(
                        new
                        {
                            id = 1,
                            bits = (short)26,
                            ch_ln = (short)26,
                            ch_loc = (short)0,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fac = (short)-1,
                            fc_ln = (short)0,
                            fc_loc = (short)-1,
                            flag = (short)0,
                            function_id = (short)1,
                            ic_ln = (short)0,
                            ic_loc = (short)-1,
                            is_active = true,
                            is_default = true,
                            location_id = 0,
                            name = "26-bit Wiegand",
                            offset = (short)0,
                            pe_ln = (short)0,
                            pe_loc = (short)-1,
                            po_ln = (short)0,
                            po_loc = (short)-1,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            bits = (short)32,
                            ch_ln = (short)32,
                            ch_loc = (short)0,
                            component_id = (short)1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fac = (short)-1,
                            fc_ln = (short)0,
                            fc_loc = (short)-1,
                            flag = (short)0,
                            function_id = (short)1,
                            ic_ln = (short)0,
                            ic_loc = (short)-1,
                            is_active = true,
                            is_default = true,
                            location_id = 0,
                            name = "32-bit Wiegand",
                            offset = (short)0,
                            pe_ln = (short)0,
                            pe_loc = (short)-1,
                            po_ln = (short)0,
                            po_loc = (short)-1,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            bits = (short)37,
                            ch_ln = (short)37,
                            ch_loc = (short)0,
                            component_id = (short)2,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fac = (short)-1,
                            fc_ln = (short)0,
                            fc_loc = (short)-1,
                            flag = (short)0,
                            function_id = (short)1,
                            ic_ln = (short)0,
                            ic_loc = (short)-1,
                            is_active = true,
                            is_default = true,
                            location_id = 0,
                            name = "37-bit Wiegand",
                            offset = (short)0,
                            pe_ln = (short)0,
                            pe_loc = (short)-1,
                            po_ln = (short)0,
                            po_loc = (short)-1,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
