// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User.Infrastructure.Persistences;

#nullable disable

namespace User.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260707165405_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("Companies", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Credential", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("act_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("apb_loc")
                        .HasColumnType("smallint");

                    b.Property<short>("bits")
                        .HasColumnType("smallint");

                    b.Property<int>("card_number")
                        .HasColumnType("integer");

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("deact_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("fac")
                        .HasColumnType("smallint");

                    b.Property<int>("flag")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<short>("issue_code")
                        .HasColumnType("smallint");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("pin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<short>("use_count")
                        .HasColumnType("smallint");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Credentials", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("company_id")
                        .HasColumnType("integer");

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.HasIndex("company_id");

                    b.ToTable("Departments", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Position", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("department_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.HasIndex("department_id");

                    b.ToTable("Positions", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.UserAdditional", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("additional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<int>("userid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("UserAdditionals", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.UserFlag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("UserFlags", "user");

                    b.HasData(
                        new
                        {
                            id = 1,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Active cardholder record",
                            is_active = true,
                            is_default = false,
                            label = "Active",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 1
                        },
                        new
                        {
                            id = 2,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Allow one free anti-passback pass",
                            is_active = true,
                            is_default = false,
                            label = "One free APB",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 2
                        },
                        new
                        {
                            id = 3,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Anti-passback exempt",
                            is_active = true,
                            is_default = false,
                            label = "APB Exempt",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 4
                        },
                        new
                        {
                            id = 4,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Use timing parameters for the disabled (ADA)",
                            is_active = true,
                            is_default = false,
                            label = "ADA",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 8
                        },
                        new
                        {
                            id = 5,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Use timing parameters for the disabled (ADA)",
                            is_active = true,
                            is_default = false,
                            label = "ADA",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 8
                        },
                        new
                        {
                            id = 6,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "PIN Exempt for 'Card & PIN' ACR mode",
                            is_active = true,
                            is_default = false,
                            label = "PIN Exempt",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 16
                        },
                        new
                        {
                            id = 7,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Do not change apb_loc",
                            is_active = true,
                            is_default = false,
                            label = "No Change APB Location",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 32
                        },
                        new
                        {
                            id = 8,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Do not alter either the 'original' or the 'current' use count values",
                            is_active = true,
                            is_default = false,
                            label = "No Change Use Limit",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 64
                        },
                        new
                        {
                            id = 9,
                            component_id = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Do not alter the 'current' use count but change the original use limit stored in the cardholder database",
                            is_active = true,
                            is_default = false,
                            label = "No Change Current",
                            location_id = 0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            value = 128
                        });
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.UserGroup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("group_id")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("UserGroups", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("company_id")
                        .HasColumnType("integer");

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("department_id")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("flag")
                        .HasColumnType("integer");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("middle_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("position_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("vacation_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("company_id");

                    b.HasIndex("department_id");

                    b.HasIndex("position_id");

                    b.HasIndex("vacation_id")
                        .IsUnique();

                    b.ToTable("Users", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Vacation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("vacation_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("vacation_day")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.ToTable("Vacations", "user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Credential", b =>
                {
                    b.HasOne("User.Infrastructure.Persistences.Entities.Users", "user")
                        .WithMany("credentials")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Department", b =>
                {
                    b.HasOne("User.Infrastructure.Persistences.Entities.Company", "company")
                        .WithMany("departments")
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Position", b =>
                {
                    b.HasOne("User.Infrastructure.Persistences.Entities.Department", "department")
                        .WithMany("positions")
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.UserAdditional", b =>
                {
                    b.HasOne("User.Infrastructure.Persistences.Entities.Users", "user")
                        .WithMany("additionals")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.UserGroup", b =>
                {
                    b.HasOne("User.Infrastructure.Persistences.Entities.Users", "user")
                        .WithMany("user_groups")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Users", b =>
                {
                    b.HasOne("User.Infrastructure.Persistences.Entities.Company", "company")
                        .WithMany("users")
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.Infrastructure.Persistences.Entities.Department", "department")
                        .WithMany("users")
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.Infrastructure.Persistences.Entities.Position", "position")
                        .WithMany("users")
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.Infrastructure.Persistences.Entities.Vacation", "vacation")
                        .WithOne("users")
                        .HasForeignKey("User.Infrastructure.Persistences.Entities.Users", "vacation_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("company");

                    b.Navigation("department");

                    b.Navigation("position");

                    b.Navigation("vacation");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Company", b =>
                {
                    b.Navigation("departments");

                    b.Navigation("users");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Department", b =>
                {
                    b.Navigation("positions");

                    b.Navigation("users");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Position", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Users", b =>
                {
                    b.Navigation("additionals");

                    b.Navigation("credentials");

                    b.Navigation("user_groups");
                });

            modelBuilder.Entity("User.Infrastructure.Persistences.Entities.Vacation", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
