// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Operator.Infrastructure.Persistences;

#nullable disable

namespace Operator.Infrastructure.Migrations
{
    [DbContext(typeof(OperatorDbContext))]
    partial class OperatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operator")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.OperatorLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<int>("operator_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("id");

                    b.HasIndex("operator_id");

                    b.ToTable("operator_locations", "operator");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_active = true,
                            location_id = 1,
                            operator_id = 1,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.Operators", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("operators", "operator");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "admin@sentrix.com",
                            firstname = "Administrator",
                            gender = "M",
                            is_active = true,
                            lastname = "",
                            middlename = "",
                            mobile = "1234567890",
                            password = "100000.lG1/4V/VRPZsbhf/Zqc4xw==.6vYcf+wEMSgqcaNhoZEdM9PaPxx2ZUErZhQbeMxo5OY=",
                            role_id = 1,
                            title = "Administrator",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            username = "admin"
                        });
                });

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.PasswordRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("is_digit")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_lower")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_symbol")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_upper")
                        .HasColumnType("boolean");

                    b.Property<int>("len")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("password_rules", "operator");

                    b.HasData(
                        new
                        {
                            id = 1,
                            is_digit = false,
                            is_lower = false,
                            is_symbol = false,
                            is_upper = false,
                            len = 4
                        });
                });

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.WeakPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("password_rule_id")
                        .HasColumnType("integer");

                    b.Property<string>("pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("password_rule_id");

                    b.ToTable("weak_passwords", "operator");

                    b.HasData(
                        new
                        {
                            id = 1,
                            password_rule_id = 1,
                            pattern = "P@ssw0rd"
                        },
                        new
                        {
                            id = 2,
                            password_rule_id = 1,
                            pattern = "password"
                        },
                        new
                        {
                            id = 3,
                            password_rule_id = 1,
                            pattern = "admin"
                        },
                        new
                        {
                            id = 4,
                            password_rule_id = 1,
                            pattern = "123456"
                        });
                });

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.OperatorLocation", b =>
                {
                    b.HasOne("Operator.Infrastructure.Persistences.Entities.Operators", "operators")
                        .WithMany("operator_locations")
                        .HasForeignKey("operator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("operators");
                });

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.WeakPassword", b =>
                {
                    b.HasOne("Operator.Infrastructure.Persistences.Entities.PasswordRule", "password_rule")
                        .WithMany("weaks")
                        .HasForeignKey("password_rule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("password_rule");
                });

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.Operators", b =>
                {
                    b.Navigation("operator_locations");
                });

            modelBuilder.Entity("Operator.Infrastructure.Persistences.Entities.PasswordRule", b =>
                {
                    b.Navigation("weaks");
                });
#pragma warning restore 612, 618
        }
    }
}
