// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Time.Infrastructure.Persistences;

#nullable disable

namespace Time.Infrastructure.Migrations
{
    [DbContext(typeof(TimeDbContext))]
    [Migration("20260713085833_UpdateTable2")]
    partial class UpdateTable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("time")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.DayInWeek", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("friday")
                        .HasColumnType("boolean");

                    b.Property<Guid>("guid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("interval_guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("monday")
                        .HasColumnType("boolean");

                    b.Property<bool>("saturday")
                        .HasColumnType("boolean");

                    b.Property<bool>("sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("interval_guid")
                        .IsUnique();

                    b.ToTable("DayInWeeks", "time");

                    b.HasData(
                        new
                        {
                            id = 1,
                            friday = true,
                            guid = new Guid("4e7a2d90-3b8f-4fd8-9c57-2a1e6b9d8f43"),
                            interval_guid = new Guid("f2d4c8b3-91aa-4b4c-8e1d-73c1f9b2a6d4"),
                            monday = true,
                            saturday = true,
                            sunday = true,
                            thursday = true,
                            tuesday = true,
                            wednesday = true
                        });
                });

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.Holiday", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("Holidays", "time");
                });

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.Interval", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<Guid>("day_in_week_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("days_detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("end")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("guid")
                        .HasColumnType("uuid");

                    b.Property<string>("start")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("timezone_guid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("timezone_guid");

                    b.ToTable("Intervals", "time");

                    b.HasData(
                        new
                        {
                            id = 1,
                            component_id = (short)1,
                            day_in_week_guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            days_detail = "",
                            end = "23:00",
                            guid = new Guid("f2d4c8b3-91aa-4b4c-8e1d-73c1f9b2a6d4"),
                            start = "00:00",
                            timezone_guid = new Guid("9b6e1f89-6f6e-4c5d-a0a5-c9d6f5d18e7b")
                        });
                });

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.TimeZone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("active")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("deactive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<short>("mode")
                        .HasColumnType("smallint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("Timezones", "time");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = "",
                            component_id = (short)1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deactive = "",
                            guid = new Guid("9b6e1f89-6f6e-4c5d-a0a5-c9d6f5d18e7b"),
                            is_active = true,
                            is_default = true,
                            location_id = 0,
                            mode = (short)1,
                            name = "Always",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            active = "",
                            component_id = (short)2,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deactive = "",
                            guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            is_active = true,
                            is_default = true,
                            location_id = 0,
                            mode = (short)0,
                            name = "Never",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.DayInWeek", b =>
                {
                    b.HasOne("Time.Infrastructure.Persistences.Entities.Interval", "interval")
                        .WithOne("days")
                        .HasForeignKey("Time.Infrastructure.Persistences.Entities.DayInWeek", "interval_guid")
                        .HasPrincipalKey("Time.Infrastructure.Persistences.Entities.Interval", "guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("interval");
                });

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.Interval", b =>
                {
                    b.HasOne("Time.Infrastructure.Persistences.Entities.TimeZone", "timezone")
                        .WithMany("intervals")
                        .HasForeignKey("timezone_guid")
                        .HasPrincipalKey("guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("timezone");
                });

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.Interval", b =>
                {
                    b.Navigation("days")
                        .IsRequired();
                });

            modelBuilder.Entity("Time.Infrastructure.Persistences.Entities.TimeZone", b =>
                {
                    b.Navigation("intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
