// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Output.Infrastructure.Persistences;

#nullable disable

namespace Output.Infrastructure.Migrations
{
    [DbContext(typeof(OutputDbContext))]
    [Migration("20260518114652_AddRelayMode")]
    partial class AddRelayMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("output")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Output.Infrastructure.Persistences.Entities.Outputs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("module_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("output_no")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("Outputs", "output");
                });

            modelBuilder.Entity("Output.Infrastructure.Persistences.Entities.RelayMode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("offline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("RelayModes", "output");

                    b.HasData(
                        new
                        {
                            id = 1,
                            mode = "Normal",
                            offline = "No Change",
                            value = 0
                        },
                        new
                        {
                            id = 2,
                            mode = "Normal",
                            offline = "Inactive",
                            value = 16
                        },
                        new
                        {
                            id = 3,
                            mode = "Normal",
                            offline = "Active",
                            value = 32
                        },
                        new
                        {
                            id = 4,
                            mode = "Inverted",
                            offline = "No Change",
                            value = 1
                        },
                        new
                        {
                            id = 5,
                            mode = "Inverted",
                            offline = "Inactive",
                            value = 16
                        },
                        new
                        {
                            id = 6,
                            mode = "Inverted",
                            offline = "Active",
                            value = 33
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
