// <auto-generated />
using System;
using Group.Infrastructure.Persistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Group.Infrastructure.Migrations
{
    [DbContext(typeof(GroupDbContext))]
    [Migration("20260707165648_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("group")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Group.Infrastructure.Persistences.Entities.GroupDoor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("group_id")
                        .HasColumnType("integer");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("group_id");

                    b.ToTable("GroupDoors", "group");
                });

            modelBuilder.Entity("Group.Infrastructure.Persistences.Entities.GroupDoorDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("door_component_id")
                        .HasColumnType("smallint");

                    b.Property<int>("group_door_id")
                        .HasColumnType("integer");

                    b.Property<short>("timezone_component_id")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.HasIndex("group_door_id");

                    b.ToTable("GroupDoorDetails", "group");
                });

            modelBuilder.Entity("Group.Infrastructure.Persistences.Entities.Groups", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("component_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("Groups", "group");

                    b.HasData(
                        new
                        {
                            id = 1,
                            component_id = (short)1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_active = true,
                            is_default = true,
                            location_id = 0,
                            name = "Allow",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            component_id = (short)2,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_active = true,
                            is_default = true,
                            location_id = 0,
                            name = "Never",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Group.Infrastructure.Persistences.Entities.GroupDoor", b =>
                {
                    b.HasOne("Group.Infrastructure.Persistences.Entities.Groups", "groups")
                        .WithMany("group_doors")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("groups");
                });

            modelBuilder.Entity("Group.Infrastructure.Persistences.Entities.GroupDoorDetail", b =>
                {
                    b.HasOne("Group.Infrastructure.Persistences.Entities.GroupDoor", "group_door")
                        .WithMany("group_door_detail")
                        .HasForeignKey("group_door_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("group_door");
                });

            modelBuilder.Entity("Group.Infrastructure.Persistences.Entities.GroupDoor", b =>
                {
                    b.Navigation("group_door_detail");
                });

            modelBuilder.Entity("Group.Infrastructure.Persistences.Entities.Groups", b =>
                {
                    b.Navigation("group_doors");
                });
#pragma warning restore 612, 618
        }
    }
}
